# Global settings
add_newline = false
command_timeout = 1000
# Left side: git branch and directory
format = """$git_branch$directory$character"""
palette = "catppuccin_mocha"
# Right side: python
# right_format = """$aws$terraform$python$nodejs"""

[battery]
disabled = true

[character]
vicmd_symbol = "[N] >>>"
success_symbol = '[‚ûú](bold green)'

[cmd_duration]
disabled = true

[container]
format = '[$symbol \[$name\]]($style) '
disabled = true

[directory]
format = ' [$path]($style) '
style = 'bold blue'
truncation_length = 1
truncation_symbol = ''
disabled = false

[directory.substitutions]
'~/tests/starship-custom' = 'work-project'

[docker_context]
disabled = true

[git_branch]
symbol = 'üå± '
format = '[$symbol$branch]($style)'
style = 'bold green'
truncation_length = 20
truncation_symbol = '‚Ä¶'

[git_status]
disabled = true

[terraform]
format = '[$symbol$workspace]($style) '
style = 'bold purple'
symbol = 'üì¶'
disabled = false

[jobs]
disabled = true

[kubernetes]
symbol = '‚ò∏ '
disabled = true
detect_files = ['Dockerfile']
format = '[$symbol$context( \($namespace\))]($style) '
contexts = [
  { context_pattern = "arn:aws:eks:us-west-2:577926974532:cluster/zd-pvc-omer", style = "green", context_alias = "jarryngandjui", symbol = " " },
]

[netns]
disabled = true

[nodejs]
format = '[$symbol($version )]($style) '
style = 'bold green'
symbol = '‚¨¢'
disabled = false

[python]
format = '[$symbol$pyenv_prefix($version )($virtualenv)]($style) '
style = 'bold yellow'
symbol = 'üêç'
pyenv_prefix = 'pyenv '
pyenv_version_name = true

[os]
disabled = true

[palettes.catppuccin_mocha]
rosewater = "#f5e0dc"
flamingo = "#f2cdcd"
pink = "#f5c2e7"
mauve = "#cba6f7"
red = "#f38ba8"
maroon = "#eba0ac"
peach = "#fab387"
yellow = "#f9e2af"
green = "#a6e3a1"
teal = "#94e2d5"
sky = "#89dceb"
sapphire = "#74c7ec"
blue = "#89b4fa"
lavender = "#b4befe"
text = "#cdd6f4"
subtext1 = "#bac2de"
subtext0 = "#a6adc8"
overlay2 = "#9399b2"
overlay1 = "#7f849c"
overlay0 = "#6c7086"
surface2 = "#585b70"
surface1 = "#45475a"
surface0 = "#313244"
base = "#1e1e2e"
mantle = "#181825"
crust = "#11111b"

[singularity]
disabled = true
